CREATE TABLE NOTICE
(
     ID		NUMBER,
     TITLE 		NVARCHAR2(100),
     WRITER_ID	NVARCHAR2(50),
     CONTENT	CLOB,
     REGDATE  	TIMESTAMP,
     HIT		NUMBER,
     FILES		NVARCHAR2(1000)
);

CREATE TABLE "COMMENT"
(
     ID		NUMBER,
     CONTENT	NVARCHAR2(2000),
     REGDATE  	TIMESTAMP,
     WRITER_ID	NVARCHAR2(50),
     NOTICE_ID	NUMBER
);

CREATE TABLE ROLE
(
     ID		VARCHAR2(50),
     DISCRIPTION 	NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
     MEMBER_ID	NVARCHAR2(50),
     ROLE_ID		VARCHAR2(50)
);

commit;


SELECT * FROM NOTICE;
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, '연락 바랍니다. 010-1111-1111', 'quest','연락처를 남깁니다',sysdate,3, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'ㅎㅇㅎㅇ', 'quest','연락처를 남깁니다',sysdate,3, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'test', '수택동 카리나','ㅇㅇ',sysdate,23, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'test', '수택동 윈터','엥',sysdate,13, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'test', '뀨','ㅎㅇ',sysdate,53, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'test1', '망우동사람','ㄴㄴㄴ',sysdate,0, null);
INSERT INTO NOTICE VALUES(ID_SEQ.NEXTVAL, 'test', '프로당근러','죠리퐁',sysdate,1, null);
CREATE SEQUENCE ID_SEQ;