--getNoticeList
SELECT ROWNUM, NOTICE.* FROM NOTICE ORDER BY REGDATE DESC;


--서브쿼리를 이용
SELECT * FROM (
SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTICE ORDER BY REGDATE DESC) N

)

WHERE ROWNUM BETWEEN 6 AND 10;

SELECT * FROM (
SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
NOTICE.* FROM NOTICE
)
WHERE NUM BETWEEN 6 AND 10;

SELECT * FROM NOTICE WHERE ID = (SELECT ID FROM NOTICE WHERE REGDATE > (SELECT REGDATE FROM NOTICE WHERE ID = 3) AND ROWNUM =1);

SELECT ID FROM (SELECT * FROM NOTICE ORDER BY REGDATE DESC)
WHERE REGDATE < (SELECT REGDATE FROM NOTICE WHERE ID = 3) AND ROWNUM =1;
--getNoticeCount

--getNotice

--getNextNotice

--getPrevNotice